// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARPApRQ5vti1qErZgd7gL4nuh2B-YhSRk',
    appId: '1:659360138850:web:e9884aa9418abbf44bb33b',
    messagingSenderId: '659360138850',
    projectId: 'singinfirebase-e41ee',
    authDomain: 'singinfirebase-e41ee.firebaseapp.com',
    storageBucket: 'singinfirebase-e41ee.appspot.com',
    measurementId: 'G-ZHEK6FXJET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrJlMkbeYSG5bnzuOgoYRMeYIMoLfho10',
    appId: '1:659360138850:android:99a60d4d848ad7e64bb33b',
    messagingSenderId: '659360138850',
    projectId: 'singinfirebase-e41ee',
    storageBucket: 'singinfirebase-e41ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUA8GU6AuypB8pZ4pUscoQsM_Zw3OgGCs',
    appId: '1:659360138850:ios:7bb7d6b52b04e9e04bb33b',
    messagingSenderId: '659360138850',
    projectId: 'singinfirebase-e41ee',
    storageBucket: 'singinfirebase-e41ee.appspot.com',
    androidClientId: '659360138850-365p6mvho9fqihpqd37d1gm75mrt2t00.apps.googleusercontent.com',
    iosClientId: '659360138850-ohgf8mbbnb6hj0sl4nnerh5509hnmcj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flow3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUA8GU6AuypB8pZ4pUscoQsM_Zw3OgGCs',
    appId: '1:659360138850:ios:7bb7d6b52b04e9e04bb33b',
    messagingSenderId: '659360138850',
    projectId: 'singinfirebase-e41ee',
    storageBucket: 'singinfirebase-e41ee.appspot.com',
    androidClientId: '659360138850-365p6mvho9fqihpqd37d1gm75mrt2t00.apps.googleusercontent.com',
    iosClientId: '659360138850-ohgf8mbbnb6hj0sl4nnerh5509hnmcj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flow3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARPApRQ5vti1qErZgd7gL4nuh2B-YhSRk',
    appId: '1:659360138850:web:acbf6ae04cfd8bc34bb33b',
    messagingSenderId: '659360138850',
    projectId: 'singinfirebase-e41ee',
    authDomain: 'singinfirebase-e41ee.firebaseapp.com',
    storageBucket: 'singinfirebase-e41ee.appspot.com',
    measurementId: 'G-5ESQXX25D8',
  );
}
