// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPbJ5D41zoyRTZNbkh49T2Gjn47HLXNWc',
    appId: '1:822010349951:android:086a1f307dc9a6c29db24a',
    messagingSenderId: '822010349951',
    projectId: 'botnoivoice-1ff7a',
    databaseURL:
        'https://botnoivoice-1ff7a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'botnoivoice-1ff7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApGk4ulnwN_-arMKBbBGhfccjwGwY18pM',
    appId: '1:822010349951:ios:f573f764b8bb47569db24a',
    messagingSenderId: '822010349951',
    projectId: 'botnoivoice-1ff7a',
    databaseURL:
        'https://botnoivoice-1ff7a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'botnoivoice-1ff7a.appspot.com',
    androidClientId:
        '822010349951-4d7ekr9mbjo5p06fkbalpgmerkfnl7rg.apps.googleusercontent.com',
    iosClientId:
        '822010349951-3bru1dkr2noookdn7n3ln3j80j976lfn.apps.googleusercontent.com',
    iosBundleId: 'com.botnoimobile.botnoivoice',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyKcAh_UFkzni3EyiiZBBMReoT56uFo2I',
    appId: '1:67359939635:web:2582fa853dd6d366ec9746',
    messagingSenderId: '67359939635',
    projectId: 'botnoi-ui-80071',
    authDomain: 'botnoi-ui-80071.firebaseapp.com',
    storageBucket: 'botnoi-ui-80071.firebasestorage.app',
    measurementId: 'G-H7N0RTFJ06',
  );
}
