import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:google_fonts/google_fonts.dart';

class GenskriptAutoGenerateDialog extends StatelessWidget {
  final int points;
  final VoidCallback onConfirm;

  const GenskriptAutoGenerateDialog({
    super.key,
    required this.points,
    required this.onConfirm,
  });

  @override
  Widget build(BuildContext context) {
    return Dialog(
      backgroundColor: Colors.white,
      surfaceTintColor: Colors.white,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20.r)),
      child: Padding(
        padding: EdgeInsets.all(24.w),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            // ปุ่มกากบาทปิด (X)
            Align(
              alignment: Alignment.topRight,
              child: InkWell(
                onTap: () => Navigator.pop(context),
                child: Icon(Icons.close, size: 24.sp, color: Colors.black54),
              ),
            ),

            // ไอคอนวงกลมสีฟ้าลูกศรคู่
            Container(
              width: 70.w,
              height: 70.w,
              decoration: const BoxDecoration(
                color: Color(0xFF00BFFF),
                shape: BoxShape.circle,
              ),
              child: Center(
                child: Container(
                  width: 50.w,
                  height: 50.w,
                  decoration: const BoxDecoration(
                    color: Colors.white,
                    shape: BoxShape.circle,
                  ),
                  child: Icon(
                    Icons.keyboard_double_arrow_right_rounded,
                    color: const Color(0xFF00BFFF),
                    size: 36.sp,
                  ),
                ),
              ),
            ),
            SizedBox(height: 20.h),

            // หัวข้อ
            Text(
              "เริ่มสร้างเสียงอัตโนมัติ?",
              style: GoogleFonts.prompt(
                fontSize: 18.sp,
                fontWeight: FontWeight.bold,
                color: Colors.black,
              ),
            ),
            SizedBox(height: 12.h),

            // ข้อความอธิบาย
            Text(
              "ระบบจะทำการสร้างเสียงอัตโนมัติ \nโดยหักพอยท์ตามจำนวนตัวอักษร \nหลังจากนั้นคุณสามารถดาวน์โหลดไฟล์ได้\nโดยที่ไม่ต้องเสียพอยท์อีกครั้ง\n\nคุณต้องการที่จะดำเนินการหรือไม่",
              textAlign: TextAlign.center,
              style: GoogleFonts.prompt(
                fontSize: 12.sp,
                color: Colors.grey[700],
                height: 1.5,
              ),
            ),
            SizedBox(height: 20.h),

            // กล่องแสดงจำนวนพอยท์
            Container(
              width: double.infinity,
              padding: EdgeInsets.symmetric(vertical: 16.h),
              decoration: BoxDecoration(
                border: Border.all(color: const Color(0xFF00BFFF), width: 1.5),
                borderRadius: BorderRadius.circular(12.r),
              ),
              child: Column(
                children: [
                  Text(
                    "จำนวนพอยท์ที่ใช้",
                    style: GoogleFonts.prompt(
                      fontSize: 14.sp,
                      fontWeight: FontWeight.bold,
                      color: const Color(0xFF1B365D),
                    ),
                  ),
                  SizedBox(height: 8.h),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      // ไอคอนตัว P
                      Container(
                        padding: EdgeInsets.all(4.w),
                        decoration: const BoxDecoration(
                          color: Color(0xFF335C7D),
                          shape: BoxShape.circle,
                        ),
                        child: Icon(Icons.stars,
                            color: const Color(0xFF7EDBD5), size: 16.sp),
                      ),
                      SizedBox(width: 8.w),
                      Text(
                        "$points พอยท์",
                        style: GoogleFonts.prompt(
                          fontSize: 16.sp,
                          fontWeight: FontWeight.bold,
                          color: Colors.black,
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
            SizedBox(height: 24.h),

            // ปุ่ม ยกเลิก / ตกลง
            Row(
              children: [
                Expanded(
                  child: OutlinedButton(
                    onPressed: () => Navigator.pop(context),
                    style: OutlinedButton.styleFrom(
                      padding: EdgeInsets.symmetric(vertical: 12.h),
                      side: const BorderSide(color: Color(0xFF00BFFF)),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(8.r),
                      ),
                    ),
                    child: Text(
                      "ยกเลิก",
                      style: GoogleFonts.prompt(
                        fontSize: 14.sp,
                        fontWeight: FontWeight.bold,
                        color: const Color(0xFF00BFFF),
                      ),
                    ),
                  ),
                ),
                SizedBox(width: 12.w),
                Expanded(
                  child: ElevatedButton(
                    onPressed: () {
                      Navigator.pop(context); // ปิด Dialog
                      onConfirm(); // เรียกฟังก์ชันสร้างเสียง
                    },
                    style: ElevatedButton.styleFrom(
                      padding: EdgeInsets.symmetric(vertical: 12.h),
                      backgroundColor: const Color(0xFF00BFFF),
                      elevation: 0,
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(8.r),
                      ),
                    ),
                    child: Text(
                      "ตกลง",
                      style: GoogleFonts.prompt(
                        fontSize: 14.sp,
                        fontWeight: FontWeight.bold,
                        color: Colors.white,
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
