class MarAdsMockData {
  static const Map<int, String> thAdvantage = {
    1: 'เราใช้วัตถุดิบสดใหม่และคุณภาพสูงกว่า',
    2: 'สูตรพิเศษที่ทำให้รสชาติดีกว่าและเป็นที่ชื่นชอบมากกว่า',
    3: 'เมนูหลากหลายที่ตอบโจทย์ทุกความต้องการของลูกค้า',
    4: 'บริการที่รวดเร็วและเป็นกันเองกว่า',
    5: 'มาตรฐานสุขอนามัยที่สูงกว่าทำให้มั่นใจในความปลอดภัยของอาหาร',
    6: 'เราใช้เทคโนโลยีล่าสุดที่ทันสมัยกว่า',
    7: 'ประสิทธิภาพการทำงานที่เหนือกว่าและมีประสิทธิผลสูงกว่า',
    8: 'การรับประกันและบริการหลังการขายที่ดีกว่า',
    9: 'ดีไซน์ที่ทันสมัยและสวยงามกว่า',
    10: 'ราคาที่คุ้มค่ากว่าและโปรโมชันพิเศษ',
    11: 'ใช้เนื้อผ้าที่คุณภาพสูงและทนทานกว่า',
    12: 'การออกแบบที่มีสไตล์และทันสมัยกว่า',
    13: 'สวมใส่สบายและมีความยืดหยุ่นมากกว่า',
    14: 'มีตัวเลือกหลากหลายให้เลือกมากกว่า',
    15: 'บริการที่เป็นมิตรและช่วยเหลือมากกว่า',
    16: 'เราใช้อุปกรณ์กีฬาที่คุณภาพสูงและทนทานกว่า',
    17: 'ทีมงานและโค้ชที่มีประสบการณ์และความเชี่ยวชาญกว่า',
    18: 'สถานที่และสิ่งอำนวยความสะดวกที่ทันสมัยมากกว่า',
    19: 'มาตรฐานความปลอดภัยที่สูงกว่าทำให้มั่นใจในความปลอดภัยของผู้เล่น',
    20: 'เรามีที่พักที่คุณภาพสูงและสะดวกสบายกว่า',
    21: 'บริการทัวร์ที่ครอบคลุมและมีประสบการณ์มากกว่า',
    22: 'มาตรฐานความปลอดภัยในการเดินทางที่สูงกว่า',
    23: 'การดูแลลูกค้าที่เอาใจใส่และช่วยเหลือได้ดีมากกว่า',
    24: 'โปรแกรมท่องเที่ยวที่หลากหลายและตอบโจทย์ความต้องการมากกว่า',
    25: 'เราใช้ผลิตภัณฑ์ที่คุณภาพสูงและปลอดภัยกว่า',
    26: 'บริการเฉพาะทางที่มีผู้เชี่ยวชาญให้คำแนะนำ',
    27: 'สถานที่และอุปกรณ์ที่ทันสมัยและครบครันกว่า',
    28: 'ผลลัพธ์ที่เห็นได้ชัดเจนและรวดเร็วกว่า',
    29: 'มีโปรโมชั่นและแพ็คเกจพิเศษที่คุ้มค่ากว่า',
    30: 'เรามีคณาจารย์ที่มีประสบการณ์และความเชี่ยวชาญกว่า',
    31: 'หลักสูตรที่ครอบคลุมและหลากหลายกว่า',
    32: 'ใช้เทคโนโลยีการเรียนการสอนที่ทันสมัยและมีประสิทธิภาพกว่า',
    33: 'การสนับสนุนและช่วยเหลือนักเรียนที่เอาใจใส่มากกว่า',
    34: 'สภาพแวดล้อมการเรียนรู้ที่ดีและเหมาะสมกว่า',
  };

  static const Map<int, String> enAdvantage = {
    1: 'We use fresher and higher quality ingredients',
    2: 'Special recipes that make the taste better and more popular',
    3: 'A diverse menu that meets all customer needs',
    4: 'Faster and friendlier service',
    5: 'Higher hygiene standards ensure food safety',
    6: 'We use the latest and more advanced technology',
    7: 'Superior work efficiency and effectiveness',
    8: 'Better warranty and after-sales service',
    9: 'More modern and attractive design',
    10: 'More cost-effective pricing and special promotions',
    11: 'Uses higher quality and more durable fabrics',
    12: 'More stylish and modern designs',
    13: 'More comfortable and flexible wear',
    14: 'More variety of choices available',
    15: 'Friendlier and more helpful service',
    16: 'We use higher quality and more durable sports equipment',
    17: 'A team and coaches with more experience and expertise',
    18: 'More modern facilities and amenities',
    19: 'Higher safety standards ensure player safety',
    20: 'We offer higher quality and more comfortable accommodations',
    21: 'More comprehensive and experienced tour services',
    22: 'Higher safety standards in travel',
    23: 'More attentive and helpful customer care',
    24: 'A more diverse and tailored travel program',
    25: 'We use higher quality and safer products',
    26: 'Specialized services with expert advice',
    27: 'More modern and well-equipped locations and facilities',
    28: 'Faster and more visible results',
    29: 'More valuable promotions and special packages',
    30: 'Our faculty has more experience and expertise',
    31: 'More comprehensive and diverse courses',
    32: 'Uses more modern and efficient teaching technologies',
    33: 'More caring and supportive student assistance',
    34: 'A better and more suitable learning environment',
  };

  static const Map<int, String> thReason = {
    1: 'ประหยัดเวลาในการทำงาน',
    2: 'ความสะดวกสบายในการใช้ชีวิต',
    3: 'คุณภาพการใช้งานที่ดีกว่า',
    4: 'เพิ่มประสิทธิภาพการทำงาน',
    5: 'มีประโยชน์ต่อสุขภาพ',
    6: 'ประหยัดเงินในระยะยาว',
    7: 'มีความน่าเชื่อถือ',
    8: 'ฟีเจอร์เทคโนโลยีตอบโจทย์ขั้นสูง',
    9: 'รับความพึงพอใจและความสุขมากยิ่งขึ้น',
    10: 'รู้สึกดีกับตัวเองเมื่อใช้งาน',
    11: 'เพิ่มความมีสไตล์และความหรูหราของคุณ',
    12: 'อิ่มอร่อยเติมท้อง',
    13: 'รสชาติที่ทำให้นึกถึงวัยเด็ก',
    14: 'ทนทาน ไม่เสียหายง่าย ใช้ได้นาน',
    15: 'สวยเด่น ทุกคนเหลียวหลัง',
    16: 'รสชาติอร่อยพร้อมสุขภาพที่ดี',
    17: 'บริการหลังการขายที่เข้าถึงง่าย',
    18: 'สวมใส่สบายในอากาศร้อน',
    19: 'ไม่มีอันตรายขณะใช้งาน',
    20: 'ได้ประสบการณ์ที่น่าจดจำ',
    21: 'มีความหลากหลาย ไม่น่าเบื่อ',
    22: 'บริการดูแลและเอาใจใส่',
    23: 'ช่วยปรับปรุงคุณภาพชีวิต',
    24: 'ประสบการณ์ที่หาไม่ได้อีก',
  };

  static const Map<int, String> enReason = {
    1: 'Saves time at work',
    2: 'Convenience in daily life',
    3: 'Improved usability',
    4: 'Enhanced work efficiency',
    5: 'Beneficial to health',
    6: 'Saves money in the long term',
    7: 'Reliable',
    8: 'Advanced technology features',
    9: 'Increased satisfaction and happiness',
    10: 'Feels good when used',
    11: 'Adds style and luxury',
    12: 'Filling and delicious',
    13: 'Taste that reminds of childhood',
    14: 'Durable, not easily damaged',
    15: 'Visibly stunning, turns heads',
    16: 'Delicious taste with good health',
    17: 'Accessible after-sales service',
    18: 'Comfortable to wear in hot weather',
    19: 'Safe to use',
    20: 'Memorable experience',
    21: 'Diverse and interesting',
    22: 'Caring and attentive service',
    23: 'Helps improve quality of life',
    24: 'Unique experience',
  };
}
