allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
android {
    compileSdkVersion 34
    defaultConfig {
        applicationId "com.example.yourapp"
        minSdkVersion 16
        //noinspection OldTargetApi
        targetSdkVersion 33
        versionCode 1
        versionName "1.0"
    }
}
