name: botnoivoice
description: "Botnoi Voice Mobile"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2 # 1.0.0 คือ flutterVersionName # +1 คือ flutterVersionCode

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  gradient_borders: ^1.0.1
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  http: ^1.2.1 
  audioplayers: ^6.0.0 
  path_provider: ^2.1.3
  open_app_file: ^4.0.2
  url_launcher: ^6.0.0
  provider: ^6.1.2
  firebase_core: ^3.3.0
  firebase_analytics: ^11.2.1
  firebase_auth: ^5.1.2
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.3
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1" # flutter pub run flutter_launcher_icons:main
  flutter_lints: ^4.0.0
  build_runner: ^2.3.3 # flutter pub run build_runner build

flutter_launcher_icons: 
  image_path_android: "assets/app_icon/icon-710x599-android.png"
  image_path_ios: "assets/app_icon/icon-1024x1024-ios.png"
  android: true
  ios: true
  adaptive_icon_background: "assets/app_icon/background-620x420.png"
  adaptive_icon_foreground: "assets/app_icon/icon-foreground-432x432.png"
  adaptive_icon_monochrome: "assets/app_icon/icon-foreground-432x432.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  
flutter:
  uses-material-design: true

  assets:
    - assets/app_icon/
    - assets/images/
    - assets/images/auth_screen/
    - assets/images/gender/
    - assets/images/icon/
    - assets/images/logo/
    - assets/images/national_flag/
    - assets/square_image/

