name: demo_botnoi_voice_mobile
description: "version 0.1"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # icon
  cupertino_icons: ^1.0.6

  # pick file from storage
  file_picker: ^4.0.3

  # text to voice generate and play audio
  http: ^0.13.3
  audioplayers: ^1.0.1

  # download and save file
  dio: ^4.0.0
  path_provider: ^2.0.0

  # open file
  open_file: ^3.2.1

  # ขออนุญาตการเข้าถึงไฟล์ใน Runtime
  permission_handler: ^10.0.0

  # เพื่อเปิดไฟล์โดยใช้ URL ตรงของไฟล์ที่ดาวน์โหลดมาใหม่ โดยไม่ต้องผ่านทาง Content URI
  url_launcher: ^6.0.0

  firebase_core: "latest_version"
  firebase_auth: "latest_version"
  google_sign_in: "latest_version"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

# https://flutter.dev/custom-fonts/#from-packages