## For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
#
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx1024m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. For more details, visit
# https://developer.android.com/r/tools/gradle-multi-project-decoupled-projects
# org.gradle.parallel=true
#Wed Oct 01 12:33:09 ICT 2025
android.enableJetifier=true

# https://developer.android.com/topic/performance/app-optimization/enable-app-optimization#native-crash-support
# If you are using AGP 9.0.0 or a newer version, you don't need to set android.r8.optimizedResourceShrinking=true. 
# Optimized resource shrinking is automatically applied when isShrinkResources = true is enabled in your build configuration.
android.r8.optimizedResourceShrinking=true
android.useAndroidX=true
org.gradle.jvmargs=-Xmx2048M -Dkotlin.daemon.jvm.options\="-Xmx2048M" -Duser.country\=US -Duser.language\=en
